services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: football
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # Email para login no pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin # Senha para login no pgAdmin
    ports:
      - "18080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
